[workspace]
members = [
    "bindings/rust",
    "crates/lava-core",
    "crates/lava",
]
default-members = ["crates/lava"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
repository = "https://github.com/edgarcosta/tree-sitter-magma"

[profile.dist]
inherits = "release"
lto = "thin"
